apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: mern
spec:
  ingressClassName: nginx
  rules:
    - host: 'elb-785745099.us-east-1.elb.amazonaws.com'
      http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service:
                name: react-svc
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: express-svc 
                port:
                  number: 3001
                  
